config/routes.rb
Rails.application.routes.draw do

  resources :reminders
   root 'reminders#index'

 devise_for :users

 	devise_scope :user do
 		get "/auth/google_oauth2/callback" => "authentications#google_oauth2"
 		get "/auth/github/callback" => "authentications#github"
	 end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
	#after_create :send_mail

	def send_mail(user)
		puts "TODAY'S REMINDER"
		if !self.private
			@all = User.all
			@all.each do |u|
				UserMailer.remind_mail(self,u.email,user.email).deliver_now
			end
		else
			UserMailer.remind_mail(self,user.email,user.email).deliver_now
		end
	end
	
	def when_to_run
		self.timings
	end


	handle_asynchronously :send_mail, :run_at => Proc.new{|i| i.when_to_run }
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 

def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    unless user
        user = User.create(uid: access_token['uid'],
           email: data['email'],
           password: Devise.friendly_token[0,20]
        )
    end
    user
end

def self.from_github(auth)
    puts "<><><><><><><><>"
    puts auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      puts "<><><><><><>"
      puts user
      puts "<><><><><><>"
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

def self.new_with_session(params, session)
  super.tap do |user|
  	 if data = session["devise.google_oauth2_data"]&& session["devise.google_oauth2_data"]["extra"]["raw_info"]
  	 	user.email = data["email"] if user.email.blank?
  	 end
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	protect_from_forgery with: :exception

	def new_sessions_path(scope)
		new_user_session_path
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/authentications_controller.rb
class AuthenticationsController  < Devise::OmniauthCallbacksController
	 def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

  def github
    puts "//////////////////////"
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_github(request.env["omniauth.auth"])
    puts request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url#alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
  	redirect_to root_path
  end

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  
  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)
    @reminder.user_id = current_user.id
    @user = current_user
    puts @user.id
    respond_to do |format|  
      if @reminder.save
        UserMailer.welcome_email(@user).deliver_now
        @reminder.send_mail(@user)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:title, :body, :timings, :private, :location)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

  def github
    puts "//////////////////////"
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_github(request.env["omniauth.auth"])
    puts request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
  	redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminder_helper.rb
module ReminderHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AuthRem" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

   
    <%= javascript_include_tag "application" %>

  </head>
  <body> 
   <div class="container">
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AuthRem</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", reminders_path  %></li>
            <% if !user_signed_in? %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
            <% if user_signed_in? %>
            <li><%= link_to "Profile",edit_user_registration_path%></li>
            <li><%= link_to "logout", destroy_user_session_path,method: :delete  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <% if notice %>
             <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
             <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
  <% if !user_signed_in? && (current_page?(reminders_path)||current_page?( new_user_session_path))%>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Login with </h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li ><%= link_to image_tag("google.png"), '/auth/google_oauth2',:class => 'img-size'   %></li>
              <li><%= link_to image_tag("github.png"), '/auth/github'  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
  <% end %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->
</div>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true) do |form| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :timings %>
    <%= form.datetime_select :timings ,{ampm: true}%>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form', reminder: @reminder %>
<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<!--p id="notice"><%= notice %></p-->

<h1>Reminders</h1>

      <div class="col-lg-12">
          <a href=<%= "#{new_reminder_path}"%> >
      <button type='button' class='btn btn-primary'>New Reminder</button>
    </a><br><br>
          <div class="list-group">
           <% @reminders.each do |reminder| %>
               <% if user_signed_in? %>
                 <% if reminder.user_id==current_user.id&& reminder.private? %>
                  <a href=<%= "#{reminder_path(reminder)}"%> class = "list-group-item list-group-item-action " style ="padding:12px">
                    <div class = "container">
                      <div class = "row">
                        <div class="col-lg-3 float-left"><h3><%= reminder.title%></h3>
                        </div>
                        <div class="col-lg-3 float-right"><h5><%= reminder.timings%></h5>
                        </div>
                      </div>
                    </div>
                  </a>
                  <% end %>
                  <%end %>
                  <% if !reminder.private? %>
                  <a href=<%= "#{reminder_path(reminder)}"%> class = "list-group-item list-group-item-action " style ="padding:12px">
                    <div class = "container">
                      <div class = "row">
                        <div class="col-lg-3 float-left"><h3><%= reminder.title%></h3>
                        </div>
                        <div class="col-lg-3 float-right"><h5><%= reminder.timings%></h5>
                        </div>
                      </div>
                    </div>
                  </a>
                <% end %>
           <% end %>
          </div><!--/.well -->
      </div><!--/span-->  
<br>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form', reminder: @reminder %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<div class="panel panel-primary">
      <div class="panel-heading">  
        <p><strong>REMINDER :  </strong><%= @reminder.title %></p>
      </div>
      <div class="panel-body">
        
    <p>
        <strong>Body:</strong>
        <%= @reminder.body %>
    </p>

     <p>
        <strong>Timings:</strong>
        <%= @reminder.timings %>
     </p>

    <p>
      <strong>Location:</strong>
      <%= @reminder.location %>
    </p>


    <p><%= link_to 'Back', reminders_path %></p>
      </div>
</div>